-- ============================================================
-- PHASE 4 · Stage 9a — Booking canonical identity + ticket token
-- ============================================================
-- Additive only. Adds three nullable columns to `bookings`:
--   • event_id      → FK to event_dates(id), ON DELETE SET NULL
--   • product_id    → FK to products(id),    ON DELETE SET NULL
--   • ticket_token  → opaque, unique, server-generated token for the MVP
--     booking-level QR ticket (Stage 9c/9d)
--
-- Why nullable, not NOT NULL: existing bookings pre-date this column and
-- must remain valid rows — no backfill is performed here (out of scope;
-- not required for New in Bangkok, which has zero historical bookings).
-- Every future read of these columns must treat NULL as "legacy booking,
-- no canonical link", not an error state.
--
-- Why ON DELETE SET NULL (not CASCADE or the default RESTRICT): a booking
-- is a financial/audit record and must never be deleted, and must never
-- BLOCK deletion of an event_dates/products row, purely because it once
-- linked to it. Mirrors event_dates.schedule_id's existing ON DELETE SET
-- NULL precedent (Migration B) rather than event_dates.product_id's
-- unqualified (RESTRICT-by-default) FK, which is appropriate there because
-- an event_dates row without its product is meaningless, but a booking
-- without its event/product link is still a valid historical record.
--
-- ticket_token is generated by application code (app/api/webhook/route.ts,
-- Stage 9b), not a DB default — keeps token format/entropy a single
-- reviewable app-side concern rather than splitting it across SQL and code.
--
-- MVP QR semantics (documented here, not schema-enforced): one Booking has
-- exactly one ticket_token and represents the WHOLE booking, including its
-- `quantity`. There is no per-guest/per-seat row. Guide books 3 spots → one
-- Booking → one QR → the host sees "3 guests" on scan, not 3 separate
-- tokens. A future per-guest ticket system would add a new `tickets` table
-- (booking_id, guest_index, ...) without touching these columns or
-- requiring a schema migration on `bookings` itself.
--
-- Rollback: additive and isolated — nothing else references these columns
-- yet, so a clean rollback is:
--   ALTER TABLE bookings DROP COLUMN IF EXISTS event_id;
--   ALTER TABLE bookings DROP COLUMN IF EXISTS product_id;
--   ALTER TABLE bookings DROP COLUMN IF EXISTS ticket_token;
-- (also drop the two indexes below first if run individually, though
-- DROP COLUMN removes any index defined on that column automatically).
-- ============================================================

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS event_id UUID REFERENCES event_dates(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS ticket_token TEXT;

-- Multiple NULLs are allowed under a plain UNIQUE index (NULL <> NULL), so
-- this does not conflict with existing/legacy bookings that have no token.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_bookings_ticket_token
  ON bookings(ticket_token);

-- Supports the check-in flow's future "open this Event Date → see its
-- bookings" query (Stage 9d) without a full-table scan.
CREATE INDEX IF NOT EXISTS idx_bookings_event_id ON bookings(event_id);
